apiVersion: v1
kind: ConfigMap
metadata:
  name: synergychat-crawler-configmap
  namespace: crawler
data:
  CRAWLER_PORT_1: "8080"
  CRAWLER_KEYWORDS: love,hate,joy,sadness,anger,disgust,fear,surpris
  CRAWLER_DB_PATH: /cache/db
  CRAWLER_PORT_2: "8081"
  CRAWLER_PORT_3: "8082"

